name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: read # Read permission is sufficient here

jobs:
  run-linters:
    name: Run linters

    runs-on: ubuntu-latest # run the checks on ubuntu

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3 # Use the latest version of the checkout action

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12.0"

      # Step 3: Install dependencies in server
      - name: Install dependencies for server
        run: npm install --prefix ./server

      # Step 4: Install dependencies in client
      - name: Install dependencies for client
        run: npm install --prefix ./client

      # Step 5: Run ESLint in client directory
      - name: Run ESLint in client directory
        run: npm run lint
        working-directory: ./client

      # Step 6: Run ESLint in server directory
      - name: Run ESLint in server directory
        run: npm run lint
        working-directory: ./server

      # Step 7: Run Prettier fix in server directory
      - name: Run Prettier fix in server directory
        run: npm run prettier-fix
        working-directory: ./server

      # Step 8: Run Prettier fix in client directory
      - name: Run Prettier fix in client directory
        run: npm run prettier-fix
        working-directory: ./client
